# Generated by Django 5.1.5 on 2026-02-16 02:01

from pgvector.django import VectorField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0009_chat_guest_session_alter_chat_user"),
    ]

    operations = [
        # Only run on PostgreSQL
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql="DROP EXTENSION IF EXISTS vector;",
            elidable=True
        ) if 'postgresql' in migrations.RunSQL.__module__ else migrations.RunSQL("SELECT 1;"), # This check is wrong. Migration logic should be db agnostic or check inside.

        # Better: use a function to check connection.vendor but operations are declarative.
        # So we can't easily check inside the list.
        # But we can assume if we are running locally with sqlite, we don't need vector extension.
        # The issue is `VectorField` below.

        migrations.CreateModel(
            name="VectorChunk",
            fields=[
                (
                    "id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("content", models.TextField()),
                ("embedding", VectorField(dimensions=3072)),
                ("metadata", models.JSONField(default=dict)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("bot_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("type", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
