from rest_framework.authentication import BaseAuthentication
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework_simplejwt.exceptions import InvalidToken, AuthenticationFailed
from django.contrib.auth.models import AnonymousUser
from django.utils import timezone
from datetime import timedelta
from .models import GuestSession
import uuid

class LenientJWTAuthentication(JWTAuthentication):
    """
    Extends JWTAuthentication to allow fallback to GuestAuthentication
    if the JWT is invalid but a Guest ID is present.
    """
    def authenticate(self, request):
        try:
            return super().authenticate(request)
        except (InvalidToken, AuthenticationFailed) as e:
            # If X-Guest-Id is present, suppress the error so GuestAuthentication can run.
            if request.headers.get('X-Guest-Id'):
                return None
            # Otherwise, raise the error as usual (blocked).
            raise e

class GuestAuthentication(BaseAuthentication):
    """
    Custom authentication to handle Guest Mode via X-Guest-Id header.
    Does NOT return a User object, but attaches request.guest_session.
    """
    def authenticate(self, request):
        guest_id = request.headers.get('X-Guest-Id')
        installation_id = request.headers.get('X-Installation-Id')
        device_label = request.headers.get('X-Guest-Device-Label')

        # 1. Idempotency: Try to reuse session by Installation ID
        if installation_id:
            # Find the most recent active session for this installation
            existing_session = GuestSession.objects.filter(
                installation_id=installation_id,
                is_active=True
            ).order_by('-created_at').first()

            if existing_session:
                # Reuse this session regardless of X-Guest-Id
                existing_session.last_seen_at = timezone.now()
                existing_session.save(update_fields=['last_seen_at'])

                request.guest_session = existing_session
                return (AnonymousUser(), None)

            # 2. Rate Limit: If creating a NEW session for this installation
            cutoff = timezone.now() - timedelta(hours=1)
            recent_count = GuestSession.objects.filter(
                installation_id=installation_id,
                created_at__gte=cutoff
            ).count()

            if recent_count >= 3:
                raise AuthenticationFailed("Too many guest sessions created. Try again later.")

        # 3. Fallback/Creation: Use X-Guest-Id
        if not guest_id:
            return None

        try:
            uuid_obj = uuid.UUID(guest_id)
        except ValueError:
            return None

        # Create or retrieve the session based on the ID generated by the client
        session, created = GuestSession.objects.get_or_create(id=uuid_obj)

        # 4. Link Installation ID
        if installation_id:
            if created:
                session.installation_id = installation_id
                session.save(update_fields=['installation_id'])
            elif session.installation_id is None:
                # Backfill installation_id for existing sessions
                session.installation_id = installation_id
                session.save(update_fields=['installation_id'])

        if created and device_label:
            session.device_label = device_label
            session.save()
        else:
            # Touch the session to update last_seen_at
            session.save()

        # Attach the session to the request for permission checks
        request.guest_session = session

        # Return AnonymousUser so request.user is not None (DRF standard)
        return (AnonymousUser(), None)
